<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class CarsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cars')->insert([
            [
                'owner_id' => 1,
                'name' => 'BMW X5',
                'engine' => '2.6L',
                'capacity' => 2600,
                'brand' => 'BMW',
                'localization' => 'Przemyśl',
                'vin' => '1HGCM82633A12BBBB',
                'gearbox' => 'Automat',
                'condition' => 'Używana',
                'color' => 'Oliwkowy',
                'country_of_origin' => 'Niemcy',
                'drive' => '4X4',
                'body' => 'Hatchback',
                'mileage' => 245678,
                'hp' => 265,
                'price' => 34000,
                'production_date' => '2010-05-15',
                'first_registration' => '2010-06-01',
                'description' => 'Zadbany, dobrze się prowadzi.',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => 'active',
                'image' => 'auto1.jpg',
                'deleted_at' => null,
            ],
            [
                'owner_id' => 1,
                'name' => 'Kia Ceed Kombi',
                'engine' => '1.5L T-GDi',
                'capacity' => 1500,
                'brand' => 'Ford',
                'localization' => 'Wrocław',
                'vin' => '1FA6P8CF0J512AAAA',
                'gearbox' => 'Manualna',
                'condition' => 'Nowy',
                'color' => 'Czerwony',
                'country_of_origin' => 'Korea Południowa',
                'drive' => 'RWD',
                'body' => 'Coupe',
                'mileage' => 67000,
                'hp' => 140,
                'price' => 53500,
                'production_date' => '2018-07-22',
                'first_registration' => '2018-08-15',
                'description' => 'Prawie jak nowy.',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => 'active',
                'image' => 'auto2.jpg',
                'deleted_at' => null,
            ],
            [
                'owner_id' => 2,
                'name' => 'Opel Astra',
                'engine' => '1.6L',
                'capacity' => 1600,
                'brand' => 'Opel',
                'localization' => 'Rzeszów',
                'vin' => '1FA6P8CF0J512OPEL',
                'gearbox' => 'Manualna',
                'condition' => 'Używany',
                'color' => 'Red',
                'country_of_origin' => 'Niemcy',
                'drive' => 'RWD',
                'body' => 'Hatchback',
                'mileage' => 215000,
                'hp' => 115,
                'price' => 15000,
                'production_date' => '2006-07-22',
                'first_registration' => '2007-08-15',
                'description' => 'Dobrze zrobiony.',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => 'active',
                'image' => 'auto3.jpg',
                'deleted_at' => null,
            ],
            [
                'owner_id' => 2,
                'name' => 'Renault Clio',
                'engine' => '1.0L',
                'capacity' => 1000,
                'brand' => 'Renault',
                'localization' => 'Kraków',
                'vin' => '1FA6P8CF0J512FIAT',
                'gearbox' => 'Manualna',
                'condition' => 'Używany',
                'color' => 'Czarny',
                'country_of_origin' => 'Francja',
                'drive' => 'FWD',
                'body' => 'Hatchback',
                'mileage' => 105000,
                'hp' => 85,
                'price' => 21000,
                'production_date' => '2014-07-22',
                'first_registration' => '2015-08-15',
                'description' => 'Sprowadzony z Anglii, kierownica po prawej stronie.',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => 'active',
                'image' => 'auto4.jpg',
                'deleted_at' => null,
            ],
            [
                'owner_id' => 3,
                'name' => 'Opel Astra J',
                'engine' => '1.6L',
                'capacity' => 1600,
                'brand' => 'Opel',
                'localization' => 'Fredropol',
                'vin' => '1FA6P8CF0J512BMMW',
                'gearbox' => 'Manualna',
                'condition' => 'Używany',
                'color' => 'Szary',
                'country_of_origin' => 'Niemcy',
                'drive' => 'FWDW',
                'body' => 'Hatchback',
                'mileage' => 255880,
                'hp' => 125,
                'price' => 23000,
                'production_date' => '2011-07-22',
                'first_registration' => '2011-08-15',
                'description' => 'Blacha do wymiany.',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => 'active',
                'image' => 'auto5.jpg',
                'deleted_at' => null,
            ],
            [
                'owner_id' => 3,
                'name' => 'Mercedes B klasa',
                'engine' => '1.7L',
                'capacity' => 1700,
                'brand' => 'Mercedes',
                'localization' => 'Wrocław',
                'vin' => '1FA6P8CF0J512MERC',
                'gearbox' => 'Manualna',
                'condition' => 'Używany',
                'color' => 'Srebrny',
                'country_of_origin' => 'Niemcy',
                'drive' => 'RWD',
                'body' => 'Hatchback',
                'mileage' => 179070,
                'hp' => 75,
                'price' => 15000,
                'production_date' => '2007-07-22',
                'first_registration' => '2007-08-15',
                'description' => 'Jeździ, skręca, hamuje.',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => 'active',
                'image' => 'default.jpg',
                'deleted_at' => null,
            ],
            [
                'owner_id' => 3,
                'name' => 'Seat Ibiza',
                'engine' => '1.9L TDI',
                'capacity' => 5000,
                'brand' => 'Seat',
                'localization' => 'Chełmno',
                'vin' => '1FA6P8CF0J512SEAT',
                'gearbox' => 'Manualna',
                'condition' => 'Używany',
                'color' => 'Czerwony',
                'country_of_origin' => 'Hiszpania',
                'drive' => 'RWD',
                'body' => 'Coupe',
                'mileage' => 208000,
                'hp' => 100,
                'price' => 4900,
                'production_date' => '2005-07-22',
                'first_registration' => '2005-08-15',
                'description' => 'Do bramy i się nie znamy.',
                'created_at' => now(),
                'updated_at' => now(),
                'status' => 'active',
                'image' => 'default.jpg',
                'deleted_at' => null,
            ],
        ]);
    }
}
